@base http://localhost:4000

### Create user
POST {{base}}/api/users
Content-Type: application/json
{
    "email": "a@example.com",
    "nickname": "hello",
    "password": "mra3Hb7yMy3Gqpf5Af7X"
}

### List User
GET {{base}}/api/users
Content-Type: application

### Get User
GET {{base}}/api/users/aaa
Content-Type: application/json
